name: timetwister.workflow

on: [push]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          if [ -f package.json ]; then npm install; fi
      - name: Lint (if available)
        run: |
          if [ -f package.json ] && npm run | grep -q "lint"; then npm run lint; else echo "No lint script"; fi